### ISSUE TITLE
Speaker using ADC MEMS microphone input instead of flash

### ISSUE THREAD

**Issue by happytm** [swharden/NumberSpeaker#1]
Thank you for publishing this library.

I have read both of your blogs. I want to drive my speaker using PWM and opamp circuit you used but on input side instead of using files for audio I want to use microphone ADC input. The quality of audio is speech quality only.

Is it possible ?

Thanks.

**Comment by swharden** [comment]
Hi @happytm, thanks for your question! It sounds like you're trying to make an Arduino device that records microphone audio and plays it back. Unfortunately I don't have any experience with this, but I recommend posting this question on the Arduino forum https://forum.arduino.cc/ and you may get some good feedback there. Good luck!

**Comment by happytm** [comment]
Thanks.
